### ISSUE TITLE
Intermittent StaleStateExceptions when using OpenID Connect authentication from UI

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper-Plugins/mdm-plugin-authentication-openid-connect#26]
Issue found while testing `mdm-explorer` UI, while logged in as a researcher via Keycloak.

I can see that multiple threads (probably from multiple simultaneous UI requests) hit OpenidConnectProvider.beforeValidate around the time of the exception.

Details in: https://github.com/MauroDataMapper/mdm-explorer/issues/456

**Comment by jamesrwelch** [comment]
Fixed by #27
