### ISSUE TITLE
OIDC authentication not supported through MS Edge

### ISSUE THREAD

**Issue by PaulChapmanPM** [MauroDataMapper-Plugins/mdm-plugin-authentication-openid-connect#3]
Ollie Freeman looked into this and confirmed it is not an API issue so he believes it is in the UI. 
Details of testing completed:

Tests conducted using ID supplied by Nicholas on his domain “oughtibridge.com”.
Test 1:
	Scenario: Log onto Mauro using the Google Chrome browser.
	Outcome: Successful log on
Test 2:
	Scenario: Log onto Mauro using the Firefox browser.
	Outcome: Successful log on
Test 3:
	Scenario: Log onto Mauro using the MS Edge browser (version 94.0.992.38 - 64-bit)
	Outcome: Fail. Did not present opportunity to enter password. Error message “Unfortunately there was a problem authorizing your login via an external provider. Details: Invalid username or password! Please try again, or contact your administrator for further support."
Test 4: 
	Scenario: Log onto Mauro using Edge in a private browser 
	Outcome: Successful log on
Test 5: 
	Scenario: Amend MS Edge settings to set "cookies and other site data" to clear on exit and restart Edge before logging on to Mauro
	Outcome: Successful log on
Test 6:
	Scenario: unset the Test 5 setting but run a one-time deletion of "cookies and other site data" before logging onto Mauro. 
	Outcome: Fail. (Same as test 3), i.e., Did not present opportunity to enter password. Error message “Unfortunately there was a problem authorizing your login via an external provider. Details: Invalid username or password! Please try again, or contact your administrator for further support."

**Comment by jamesrwelch** [comment]
I believe this issue is fixed and can now be closed?  @PaulChapmanPM @olliefreeman

**Comment by PaulChapmanPM** [comment]
This issue is indeed fixed. Thank you @olliefreeman and @jamesrwelch for your help.
